# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 17:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2017, 10, 9, 17, 41, 46, 46431, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
