# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
