# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.CharField(max_length=250),
        ),
    ]
