# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-18 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20180318_1357'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Organization',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='company',
            new_name='organization',
        ),
    ]
