# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20171027_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='project',
        ),
    ]
