# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
