# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20171110_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
