# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_interest_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.IntegerField(default=1),
        ),
    ]
