# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20171203_2346'),
        ('user', '0007_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferences',
            field=models.ManyToManyField(to='project.Keyword'),
        ),
    ]
