# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-18 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive'), (3, 'Done')], default=1),
            preserve_default=False,
        ),
    ]
