# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-30 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20171226_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(upload_to=''),
        ),
    ]
