# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-30 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20171230_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(default='https://www.w3schools.com/w3css/img_fjords.jpg', upload_to=''),
        ),
    ]
